// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Filelocker {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("DownloadScreen")]
	public partial class DownloadScreen {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UITextField __mt_txtFileId;
		
		private MonoTouch.UIKit.UILabel __mt_lblStatus;
		
		private MonoTouch.UIKit.UIButton __mt_btnDownload;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("txtFileId")]
		private MonoTouch.UIKit.UITextField txtFileId {
			get {
				this.__mt_txtFileId = ((MonoTouch.UIKit.UITextField)(this.GetNativeField("txtFileId")));
				return this.__mt_txtFileId;
			}
			set {
				this.__mt_txtFileId = value;
				this.SetNativeField("txtFileId", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("lblStatus")]
		private MonoTouch.UIKit.UILabel lblStatus {
			get {
				this.__mt_lblStatus = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("lblStatus")));
				return this.__mt_lblStatus;
			}
			set {
				this.__mt_lblStatus = value;
				this.SetNativeField("lblStatus", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("btnDownload")]
		private MonoTouch.UIKit.UIButton btnDownload {
			get {
				this.__mt_btnDownload = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("btnDownload")));
				return this.__mt_btnDownload;
			}
			set {
				this.__mt_btnDownload = value;
				this.SetNativeField("btnDownload", value);
			}
		}
	}
}
