// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Filelocker {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("FileShare")]
	public partial class FileShare {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UITableView __mt_tblShare;
		
		private MonoTouch.UIKit.UIBarButtonItem __mt_btnClose;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("tblShare")]
		private MonoTouch.UIKit.UITableView tblShare {
			get {
				this.__mt_tblShare = ((MonoTouch.UIKit.UITableView)(this.GetNativeField("tblShare")));
				return this.__mt_tblShare;
			}
			set {
				this.__mt_tblShare = value;
				this.SetNativeField("tblShare", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("btnClose")]
		private MonoTouch.UIKit.UIBarButtonItem btnClose {
			get {
				this.__mt_btnClose = ((MonoTouch.UIKit.UIBarButtonItem)(this.GetNativeField("btnClose")));
				return this.__mt_btnClose;
			}
			set {
				this.__mt_btnClose = value;
				this.SetNativeField("btnClose", value);
			}
		}
	}
}
