// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Filelocker {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("FileViewer")]
	public partial class FileViewer {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UIWebView __mt_webView;
		
		private MonoTouch.UIKit.UIBarButtonItem __mt_btnClose;
		
		private MonoTouch.UIKit.UINavigationItem __mt_nvTitle;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("webView")]
		private MonoTouch.UIKit.UIWebView webView {
			get {
				this.__mt_webView = ((MonoTouch.UIKit.UIWebView)(this.GetNativeField("webView")));
				return this.__mt_webView;
			}
			set {
				this.__mt_webView = value;
				this.SetNativeField("webView", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("btnClose")]
		private MonoTouch.UIKit.UIBarButtonItem btnClose {
			get {
				this.__mt_btnClose = ((MonoTouch.UIKit.UIBarButtonItem)(this.GetNativeField("btnClose")));
				return this.__mt_btnClose;
			}
			set {
				this.__mt_btnClose = value;
				this.SetNativeField("btnClose", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("nvTitle")]
		private MonoTouch.UIKit.UINavigationItem nvTitle {
			get {
				this.__mt_nvTitle = ((MonoTouch.UIKit.UINavigationItem)(this.GetNativeField("nvTitle")));
				return this.__mt_nvTitle;
			}
			set {
				this.__mt_nvTitle = value;
				this.SetNativeField("nvTitle", value);
			}
		}
	}
}
