// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Filelocker {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("MessageComposer")]
	public partial class MessageComposer {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UIBarButtonItem __mt_btnCancel;
		
		private MonoTouch.UIKit.UIBarButtonItem __mt_btnSend;
		
		private MonoTouch.UIKit.UITableView __mt_tblMessage;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("btnCancel")]
		private MonoTouch.UIKit.UIBarButtonItem btnCancel {
			get {
				this.__mt_btnCancel = ((MonoTouch.UIKit.UIBarButtonItem)(this.GetNativeField("btnCancel")));
				return this.__mt_btnCancel;
			}
			set {
				this.__mt_btnCancel = value;
				this.SetNativeField("btnCancel", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("btnSend")]
		private MonoTouch.UIKit.UIBarButtonItem btnSend {
			get {
				this.__mt_btnSend = ((MonoTouch.UIKit.UIBarButtonItem)(this.GetNativeField("btnSend")));
				return this.__mt_btnSend;
			}
			set {
				this.__mt_btnSend = value;
				this.SetNativeField("btnSend", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("tblMessage")]
		private MonoTouch.UIKit.UITableView tblMessage {
			get {
				this.__mt_tblMessage = ((MonoTouch.UIKit.UITableView)(this.GetNativeField("tblMessage")));
				return this.__mt_tblMessage;
			}
			set {
				this.__mt_tblMessage = value;
				this.SetNativeField("tblMessage", value);
			}
		}
	}
}
