// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Filelocker {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("MessageInfoView")]
	public partial class MessageInfoView {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UIBarButtonItem __mt_btnDelete;
		
		private MonoTouch.UIKit.UITextView __mt_txtBody;
		
		private MonoTouch.UIKit.UITextField __mt_txtSender;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("btnDelete")]
		private MonoTouch.UIKit.UIBarButtonItem btnDelete {
			get {
				this.__mt_btnDelete = ((MonoTouch.UIKit.UIBarButtonItem)(this.GetNativeField("btnDelete")));
				return this.__mt_btnDelete;
			}
			set {
				this.__mt_btnDelete = value;
				this.SetNativeField("btnDelete", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("txtBody")]
		private MonoTouch.UIKit.UITextView txtBody {
			get {
				this.__mt_txtBody = ((MonoTouch.UIKit.UITextView)(this.GetNativeField("txtBody")));
				return this.__mt_txtBody;
			}
			set {
				this.__mt_txtBody = value;
				this.SetNativeField("txtBody", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("txtSender")]
		private MonoTouch.UIKit.UITextField txtSender {
			get {
				this.__mt_txtSender = ((MonoTouch.UIKit.UITextField)(this.GetNativeField("txtSender")));
				return this.__mt_txtSender;
			}
			set {
				this.__mt_txtSender = value;
				this.SetNativeField("txtSender", value);
			}
		}
	}
}
