// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Filelocker {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("Register")]
	public partial class Register {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UIButton __mt_btnSaveSettings;
		
		private MonoTouch.UIKit.UITextField __mt_txtCLIKey;
		
		private MonoTouch.UIKit.UITextField __mt_txtPassword;
		
		private MonoTouch.UIKit.UITextField __mt_txtServer;
		
		private MonoTouch.UIKit.UITextField __mt_txtUsername;
		
		private MonoTouch.UIKit.UILabel __mt_txtError;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("btnSaveSettings")]
		private MonoTouch.UIKit.UIButton btnSaveSettings {
			get {
				this.__mt_btnSaveSettings = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("btnSaveSettings")));
				return this.__mt_btnSaveSettings;
			}
			set {
				this.__mt_btnSaveSettings = value;
				this.SetNativeField("btnSaveSettings", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("txtCLIKey")]
		private MonoTouch.UIKit.UITextField txtCLIKey {
			get {
				this.__mt_txtCLIKey = ((MonoTouch.UIKit.UITextField)(this.GetNativeField("txtCLIKey")));
				return this.__mt_txtCLIKey;
			}
			set {
				this.__mt_txtCLIKey = value;
				this.SetNativeField("txtCLIKey", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("txtPassword")]
		private MonoTouch.UIKit.UITextField txtPassword {
			get {
				this.__mt_txtPassword = ((MonoTouch.UIKit.UITextField)(this.GetNativeField("txtPassword")));
				return this.__mt_txtPassword;
			}
			set {
				this.__mt_txtPassword = value;
				this.SetNativeField("txtPassword", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("txtServer")]
		private MonoTouch.UIKit.UITextField txtServer {
			get {
				this.__mt_txtServer = ((MonoTouch.UIKit.UITextField)(this.GetNativeField("txtServer")));
				return this.__mt_txtServer;
			}
			set {
				this.__mt_txtServer = value;
				this.SetNativeField("txtServer", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("txtUsername")]
		private MonoTouch.UIKit.UITextField txtUsername {
			get {
				this.__mt_txtUsername = ((MonoTouch.UIKit.UITextField)(this.GetNativeField("txtUsername")));
				return this.__mt_txtUsername;
			}
			set {
				this.__mt_txtUsername = value;
				this.SetNativeField("txtUsername", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("txtError")]
		private MonoTouch.UIKit.UILabel txtError {
			get {
				this.__mt_txtError = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("txtError")));
				return this.__mt_txtError;
			}
			set {
				this.__mt_txtError = value;
				this.SetNativeField("txtError", value);
			}
		}
	}
}
