// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Filelocker {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("UploadView")]
	public partial class UploadView {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UIBarButtonItem __mt_btnCamera;
		
		private MonoTouch.UIKit.UIImageView __mt_imageView;
		
		private MonoTouch.UIKit.UIBarButtonItem __mt_btnClose;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("btnCamera")]
		private MonoTouch.UIKit.UIBarButtonItem btnCamera {
			get {
				this.__mt_btnCamera = ((MonoTouch.UIKit.UIBarButtonItem)(this.GetNativeField("btnCamera")));
				return this.__mt_btnCamera;
			}
			set {
				this.__mt_btnCamera = value;
				this.SetNativeField("btnCamera", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("imageView")]
		private MonoTouch.UIKit.UIImageView imageView {
			get {
				this.__mt_imageView = ((MonoTouch.UIKit.UIImageView)(this.GetNativeField("imageView")));
				return this.__mt_imageView;
			}
			set {
				this.__mt_imageView = value;
				this.SetNativeField("imageView", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("btnClose")]
		private MonoTouch.UIKit.UIBarButtonItem btnClose {
			get {
				this.__mt_btnClose = ((MonoTouch.UIKit.UIBarButtonItem)(this.GetNativeField("btnClose")));
				return this.__mt_btnClose;
			}
			set {
				this.__mt_btnClose = value;
				this.SetNativeField("btnClose", value);
			}
		}
	}
}
